import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Lemon Hive</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="assets/lib/bootstrap/bootstrap.min.css" />
        <link rel="stylesheet" href="assets/lib/layer-slider/layerslider.css" />
        <link rel="stylesheet" href="assets/lib/dc/dc-animation.css" />
        <link rel="stylesheet" href="assets/css/home-bundle.min.css" />
        <link rel="stylesheet" href="assets/css/home.css" />
      </Head>
      <main className={styles.main}>
        <section class="pokemon">
          <div class="container">
            <div class="row">
              <div class="pokemon__logo">
                <img src="/assets/images/dynamic/Logo.png" alt="" />
              </div>
            </div>
            <div class="row">
              <div class="col">
                <div class="pokemon__single">
                  <a href="inner.html"></a>
                  <div class="pokemon__single__img">
                    <img src="/assets/images/dynamic/list/1.png" alt="" />
                  </div>
                  <div class="pokemon__single__text">
                    <h4>Bulbasaur</h4>
                    <div class="pokemon__single__text__power d-flex">
                      <p class="grass">Grass</p>
                      <p class="poison">Poison</p>
                    </div>
                  </div>
                  <div class="pokemon__single__id">
                    <p>#10</p>
                  </div>
                </div>
              </div>
              <div class="col">
                <div class="pokemon__single">
                  <div class="pokemon__single__img">
                    <img src="/assets/images/dynamic/list/1.png" alt="" />
                  </div>
                  <div class="pokemon__single__text">
                    <h4>Bulbasaur</h4>
                    <div class="pokemon__single__text__power d-flex">
                      <p class="grass">Grass</p>
                      <p class="poison">Poison</p>
                    </div>
                  </div>
                  <div class="pokemon__single__id">
                    <p>#10</p>
                  </div>
                </div>

              </div>
              <div class="col">
                <div class="pokemon__single">
                  <div class="pokemon__single__img">
                    <img src="/assets/images/dynamic/list/1.png" alt="" />
                  </div>
                  <div class="pokemon__single__text">
                    <h4>Bulbasaur</h4>
                    <div class="pokemon__single__text__power d-flex">
                      <p class="grass">Grass</p>
                      <p class="poison">Poison</p>
                    </div>
                  </div>
                  <div class="pokemon__single__id">
                    <p>#10</p>
                  </div>
                </div>

              </div>
              <div class="col">
                <div class="pokemon__single">
                  <div class="pokemon__single__img">
                    <img src="/assets/images/dynamic/list/1.png" alt="" />
                  </div>
                  <div class="pokemon__single__text">
                    <h4>Bulbasaur</h4>
                    <div class="pokemon__single__text__power d-flex">
                      <p class="grass">Grass</p>
                      <p class="poison">Poison</p>
                    </div>
                  </div>
                  <div class="pokemon__single__id">
                    <p>#10</p>
                  </div>
                </div>

              </div>
              <div class="col">
                <div class="pokemon__single">
                  <div class="pokemon__single__img">
                    <img src="/assets/images/dynamic/list/1.png" alt="" />
                  </div>
                  <div class="pokemon__single__text">
                    <h4>Bulbasaur</h4>
                    <div class="pokemon__single__text__power d-flex">
                      <p class="grass">Grass</p>
                      <p class="poison">Poison</p>
                    </div>
                  </div>
                  <div class="pokemon__single__id">
                    <p>#10</p>
                  </div>
                </div>

              </div>
              <div class="col">
                <div class="pokemon__single">
                  <div class="pokemon__single__img">
                    <img src="/assets/images/dynamic/list/1.png" alt="" />
                  </div>
                  <div class="pokemon__single__text">
                    <h4>Bulbasaur</h4>
                    <div class="pokemon__single__text__power d-flex">
                      <p class="grass">Grass</p>
                      <p class="poison">Poison</p>
                    </div>
                  </div>
                  <div class="pokemon__single__id">
                    <p>#10</p>
                  </div>
                </div>

              </div>
              <div class="col">
                <div class="pokemon__single">
                  <div class="pokemon__single__img">
                    <img src="/assets/images/dynamic/list/1.png" alt="" />
                  </div>
                  <div class="pokemon__single__text">
                    <h4>Bulbasaur</h4>
                    <div class="pokemon__single__text__power d-flex">
                      <p class="grass">Grass</p>
                      <p class="poison">Poison</p>
                    </div>
                  </div>
                  <div class="pokemon__single__id">
                    <p>#10</p>
                  </div>
                </div>

              </div>
              <div class="col">
                <div class="pokemon__single">
                  <div class="pokemon__single__img">
                    <img src="/assets/images/dynamic/list/1.png" alt="" />
                  </div>
                  <div class="pokemon__single__text">
                    <h4>Bulbasaur</h4>
                    <div class="pokemon__single__text__power d-flex">
                      <p class="grass">Grass</p>
                      <p class="poison">Poison</p>
                    </div>
                  </div>
                  <div class="pokemon__single__id">
                    <p>#10</p>
                  </div>
                </div>

              </div>
              <div class="col">
                <div class="pokemon__single">
                  <div class="pokemon__single__img">
                    <img src="/assets/images/dynamic/list/1.png" alt="" />
                  </div>
                  <div class="pokemon__single__text">
                    <h4>Bulbasaur</h4>
                    <div class="pokemon__single__text__power d-flex">
                      <p class="grass">Grass</p>
                      <p class="poison">Poison</p>
                    </div>
                  </div>
                  <div class="pokemon__single__id">
                    <p>#10</p>
                  </div>
                </div>

              </div>
            </div>
          </div>
        </section>
        <section class="blog_section">
          <div class="row">
            <div class="col-md-1">
              <div class="blog_section__img">
                <img src="./assets/images/dynamic/Left.png" alt="" />
              </div>
            </div>
            <div class="col-md-10">
              <div class="blog_section__header">
                <h1 class="blog_section__header__content_header">Ash & Pikachu Arrive in
                  Pokémon Universe</h1>
              </div>
              <div class="blog_section__blog">
                <div class="row">
                  <div class="col-md-7">
                    <div class="row">
                      <div class="col-md-9">
                        <div class="blog_section__blog__text">
                          <p>Lorem ipsum dolor sit amet consectetur. Risus cursus nibh elementum ornare a aliquet
                            ac. Feugiat scelerisque ultrices
                            tempor facilisi tempus risus nunc. Proin quis morbi posuere nisl etiam scelerisque.
                            Proin pretium gravida semper ut erat
                            nisi. Pulvinar ac mattis porta amet et. Nisl urna non fames felis leo. Vitae
                            pulvinar sed viverra sit pretium lorem
                            elementum. Iaculis sit maecenas sodales mi convallis justo aliquam. Tincidunt semper
                            ut ornare vivamus lectus.</p>
                        </div>
                        <div class="row">
                          <div class="col-md-9">
                            <div class="blog_section__blog__text ">
                              <p>
                                Lorem ipsum dolor sit amet consectetur. Turpis integer massa consectetur sed
                                enim
                                quis viverra. Vestibulum eu nibh dolor
                                semper. Nisl feugiat quis nec odio pulvinar feugiat velit. Nulla massa sit
                                morbi
                                morbi. Tortor viverra eget lacus
                                feugiat. Tempus vitae vitae orci at ultrices nisi diam faucibus. Ultricies in
                                cursus volutpat aliquam turpis urna in
                                sed. Hendrerit arcu sit lectus adipiscing egestas semper nunc. Ante
                                consectetur
                                id congue pulvinar libero tristique et
                                orci. Platea convallis dictum dui augue. Tincidunt mattis urna sit semper sed
                                duis feugiat mi.
                              </p>
                            </div>

                          </div>
                          <div class="col-md-3">
                            <div class="blog_section__blog__imag">
                              <img src="./assets/images/dynamic/Image04.png" alt="" />
                            </div>
                          </div>
                        </div>
                        <div class="row">
                          <div class="col-md-12">
                            <div class="blog_section__blog__text ">
                              <p>
                                Lorem ipsum dolor sit amet consectetur. Turpis integer massa consectetur sed
                                enim
                                quis viverra. Vestibulum eu nibh dolor
                                semper. Nisl feugiat quis nec odio pulvinar feugiat velit. Nulla massa sit
                                morbi
                                morbi. Tortor viverra eget lacus
                                feugiat. Tempus vitae vitae orci at ultrices nisi diam faucibus. Ultricies in
                                cursus volutpat aliquam turpis urna in
                                sed. Hendrerit arcu sit lectus adipiscing egestas semper nunc. Ante
                                consectetur
                                id congue pulvinar libero tristique et
                                orci. Platea convallis dictum dui augue. Tincidunt mattis urna sit semper sed
                                duis feugiat mi.
                              </p>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div class="col-md-3">
                        <div class="blog_section__blog__img">
                          <img src="./assets/images/dynamic/Image03.png" alt="" />
                          <img src="./assets/images/dynamic/Image02.png" alt="" />
                        </div>
                      </div>

                    </div>

                    <div class="row">
                      <div class="col-md-12">
                        <div class="blog_section__blog__text">
                          <p>At a enim parturient id. Suspendisse ullamcorper fermentum accumsan diam tellus.
                            Nibh
                            pretium ultrices scelerisque dolor
                            at etiam lectus gravida sed. Sit in turpis suspendisse et aliquam. Vulputate sit
                            phasellus
                            proin eget arcu. Enim nec
                            ante velit erat nibh nunc amet. Tellus at sit imperdiet non. Cras dictum curabitur
                            urna
                            mauris in.
                            Ut dui odio sagittis ut imperdiet ultricies mauris ac. A sit id etiam vitae non
                            posuere
                            tristique. Morbi sit mi sed nam
                            amet tristique tellus. Sed quam aliquam pharetra nunc ipsum mattis. Volutpat
                            pellentesque
                            cras euismod habitant sit
                            nibh. Dictum odio at aliquam sed. Orci odio lacinia id sem sed suspendisse mi
                            fringilla
                            purus. Quis sed ultricies ac
                            nullam odio. Gravida sollicitudin viverra ornare pretium etiam tortor imperdiet
                            tellus. Id
                            purus etiam nunc hendrerit
                            quam in. Dui netus lectus nulla cursus ultrices nulla. Morbi sit in gravida
                            fermentum. Non
                            sed lobortis amet eget sed
                            donec.At a enim parturient id. Suspendisse ullamcorper fermentum accumsan diam
                            tellus.
                            Nibh pretium ultrices scelerisque
                            dolor at etiam lectus gravida sed. Sit in turpis suspendisse et aliquam. Vulputate
                            sit
                            phasellus proin eget arcu. Enim
                            nec ante velit erat nibh nunc amet. Tellus at sit imperdiet non. Cras dictum
                            curabitur
                            urna mauris in.
                            Ut dui odio sagittis ut imperdiet ultricies mauris ac. A sit id etiam vitae non
                            posuere
                            tristique. Morbi sit mi sed nam
                            amet tristique tellus. Sed quam aliquam pharetra nunc ipsum mattis. Volutpat
                            pellentesque
                            cras euismod habitant sit
                            nibh. Dictum odio at aliquam sed. Orci odio lacinia id sem.</p>
                        </div>
                      </div>

                    </div>

                  </div>
                  <div class="col-md-5 padding">
                    <div class="row">
                      <div class="col-md-12">
                        <div class="blog_section__blog__text">
                          <p>Lorem ipsum dolor sit amet consectetur. Risus cursus nibh elementum ornare a aliquet
                            ac. Feugiat scelerisque ultrices
                            tempor facilisi tempus risus nunc. Proin quis morbi posuere nisl etiam scelerisque.
                            Proin pretium gravida semper ut erat
                            nisi. Pulvinar ac mattis porta amet et. Nisl urna non fames felis leo. Vitae
                            pulvinar sed viverra .</p>
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-3">
                        <div class="blog_section__blog__imag">
                          <img src="./assets/images/dynamic/Image05.png" alt="" />
                        </div>
                      </div>
                      <div class="col-md-9">
                        <div class="blog_section__blog__text">
                          <p>Lorem ipsum dolor sit amet consectetur. Risus cursus nibh elementum ornare a aliquet
                            ac. Feugiat scelerisque ultrices
                            tempor facilisi tempus risus nunc. Proin quis morbi posuere nisl etiam scelerisque.
                            Proin pretium gravida semper ut erat
                            nisi. Pulvinar ac mattis porta amet et. Nisl urna non fames felis leo. Vitae
                            pulvinar sed viverra .</p>
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-3">
                        <div class="blog_section__blog__imag">
                          <img src="./assets/images/dynamic/Image01.png" alt="" />
                        </div>
                      </div>
                      <div class="col-md-9">
                        <div class="blog_section__blog__text ">
                          <p>
                            Lorem ipsum dolor sit amet consectetur. Turpis integer massa consectetur sed
                            enim
                            quis viverra. Vestibulum eu nibh dolor
                            semper. Nisl feugiat quis nec odio pulvinar feugiat velit. Nulla massa sit
                            morbi
                            morbi. Tortor viverra eget lacus
                            feugiat. Tempus vitae vitae orci at ultrices nisi diam faucibus. Ultricies in
                            cursus volutpat aliquam turpis urna in
                            sed. Hendrerit arcu sit lectus adipiscing egestas semper nunc. Ante
                            consectetur
                            id congue pulvinar libero tristique et
                            orci. Platea convallis dictum dui augue. Tincidunt mattis urna sit semper sed
                            duis feugiat mi.
                          </p>
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-12">
                        <div class="blog_section__blog__text ">
                          <p>
                            Lorem ipsum dolor sit amet consectetur. Turpis integer massa consectetur sed
                            enim
                            quis viverra. Vestibulum eu nibh dolor
                            semper. Nisl feugiat quis nec odio pulvinar feugiat velit. Nulla massa sit
                            morbi
                            morbi. Tortor viverra eget lacus
                            feugiat. Tempus vitae vitae orci at ultrices nisi diam faucibus. Ultricies in
                            cursus volutpat aliquam turpis urna in
                            sed. Hendrerit arcu sit lectus adipiscing egestas semper nunc. Ante
                            consectetur
                            id congue pulvinar libero tristique et
                            orci. Platea convallis dictum dui augue. Tincidunt mattis urna sit semper sed
                            duis feugiat mi.
                          </p>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-1">
              <div class="blog_section__img">
                <img src="./assets/images/dynamic/Left.png" alt="" />
              </div>
            </div>
          </div>
        </section>




        {/* <script src="assets/js/jquery.min.js"></script>
        <script src="assets/lib/bootstrap/bootstrap.min.js"></script>
        <script src="assets/lib/light-gallery/lightgallery.js"></script>
        <script src="assets/lib/layer-slider/layerslider.transitions.js"></script>
        <script src="assets/lib/layer-slider/layerslider.kreaturamedia.jquery.js"></script>
        <script src="assets/lib/slick-slider/slick.js"></script>
        <script src="assets/lib/gsap/tweenmax.js"></script>
        <script src="assets/lib/anim/jquery.blast.min.js"></script>
        <script src="assets/lib/nice-select/jquery.nice-select.min.js"></script>
        <script src="assets/lib/dc/image-preloader.js"></script>
        <script src="assets/lib/dc/dc-animation.js"></script>
        <script src="assets/js/global.js"></script>
        <script src="assets/js/home.js"></script> */}
      </main>
    </>
  )
}
